source 'https://rubygems.org'
source 'https://rails-assets.org'

ruby '2.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.1.0'

gem 'puma'

# For Heroku integration features
gem 'rails_12factor', group: :production

# Use postgresql as the database for Active Record
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'jquery-ui-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'devise'
gem 'cancancan'

gem 'chronic'
gem 'foreman'
# gem 'tempodb'

gem 'tempodb', git: "https://github.com/tempodb/tempodb-ruby.git", branch: "v1.0"

gem 'thor'

gem 'semantic-ui-sass'

gem 'parallel'

gem 'bootstrap-sass'
gem 'font-awesome-sass'
# gem 'bower-rails'

gem 'rails-assets-angular'
gem 'rails-assets-angular-route'
gem 'rails-assets-angular-resource'
gem 'rails-assets-angular-animate'
gem 'rails-assets-angular-cookies'
gem 'rails-assets-angular-mocks'
gem 'rails-assets-angular-ui-bootstrap-bower'
gem 'rails-assets-angular-ui-router'
gem 'rails-assets-angular-ui-utils'

group :development, :test do
  gem "jasmine", github: "pivotal/jasmine-gem"
end

gem 'angular_rails_csrf'

gem 'autoprefixer-rails'

group :development do
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-minitest'
  gem 'guard-rubocop'
  gem 'guard-rails'
  gem 'guard-jshint-on-rails'
  gem 'terminal-notifier-guard'
  gem 'quiet_assets'
  gem 'rack-mini-profiler', require: false
  gem 'flamegraph'
end

group :development, :test do
  gem 'awesome_print'
  gem 'dotenv-rails'
  gem 'spring-commands-rspec'
end

group :test do
  gem 'minitest-spec-rails'
  gem 'rr'
end

gem 'sidekiq', '~> 3.2.0'
gem 'sinatra', '>= 1.3.0', :require => nil


gem 'aws-sdk'

